## I HAVE NO IDEA WHY SETTING THESE ON TARGET BASE IS NOT WORKING AND I WANT TO FUCKING DIE

set(LINKER_EM_FLAGS "-s USE_SDL=2 -s FULL_ES3=1 -s OFFSCREEN_FRAMEBUFFER=1")
set(LINKER_EM_FLAGS "${LINKER_EM_FLAGS} -s MIN_WEBGL_VERSION=1 -s MAX_WEBGL_VERSION=2")
set(LINKER_EM_FLAGS "${LINKER_EM_FLAGS} -s ASSERTIONS=0 -s ALLOW_MEMORY_GROWTH=1 -s ASYNCIFY=1")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -sUSE_SDL=2" )
set(CMAKE_EXE_LINKER_FLAGS   "${CMAKE_EXE_LINKER_FLAGS} ${LINKER_EM_FLAGS} \
--embed-file ../external/lygia \
--embed-file ../Resources/Fonts \
--embed-file ../Resources/Textures \
--embed-file ../Resources/Shaders \
")
